export var msongsMaster = [
  {"Id":1,"CompNo":1},
  {"Id":2,"CompNo":1},
  {"Id":3,"CompNo":1},
  {"Id":4,"CompNo":1},
  {"Id":5,"CompNo":1},
  {"Id":6,"CompNo":1},
  {"Id":11,"CompNo":1},
  {"Id":12,"CompNo":1},
  {"Id":13,"CompNo":1},
  {"Id":102,"CompNo":1},
  {"Id":1003,"CompNo":1}
];

export var msongsComp = [
  {"Id":1,"Alvar":"Periyalwar","Comp":"Thirumozhi","TamAlvar":"பெரியாழ்வார்","TamComp":"திருமொழி"},
  {"Id":2,"Alvar":"Sri Andal","Comp":"Thiruppavai","TamAlvar":"ஆண்டாள்","TamComp":"திருப்பாவை"},
  {"Id":3,"Alvar":"Sri Andal","Comp":"Nachiar Tirumozhi","TamAlvar":"ஆண்டாள்","TamComp":"நாச்சியார் திருமொழி"},
  {"Id":4,"Alvar":"Kulasekara Alwar","Comp":"Perumal Thirumozhi","TamAlvar":"குலசேகராழ்வார்","TamComp":"பெருமாள் திருமொழி"},
  {"Id":5,"Alvar":"Thirumazhisai Alwar","Comp":"Thiruchchanda Viruththam","TamAlvar":"திருமழிசை ஆழ்வார்","TamComp":"திருச்சந்த விருத்தம்"},
  {"Id":6,"Alvar":"Thondaradippodi Alwar","Comp":"Thirumalai","TamAlvar":"தொண்டரடிப் பொடியாழ்வார்","TamComp":"திருமாலை"},
  {"Id":7,"Alvar":"Thondaradippodi Alwar","Comp":"Thiruppalliyezhuchchi","TamAlvar":"தொண்டரடிப் பொடியாழ்வார்","TamComp":"திருப்பள்ளியெழுச்சி"},
  {"Id":8,"Alvar":"Thiruppaan Alwar","Comp":"Amalanadhi piran","TamAlvar":"திருப்பாணாழ்வார்","TamComp":"அமலனாதிபிரான்"},
  {"Id":9,"Alvar":"Madhurakavi Alwar","Comp":"Kanni Nun Siruththambu","TamAlvar":"மதுரகவியாழ்வார்","TamComp":"கண்ணிநுண் சிறுதாம்பு"},
  {"Id":10,"Alvar":"Thirumangai Alwar","Comp":"Peria Thirumozhi","TamAlvar":"திருமங்கையாழ்வார்","TamComp":"பெரிய திருமொழி"},
  {"Id":11,"Alvar":"Thirumangai Alwar","Comp":"Kurun Thandagam","TamAlvar":"திருமங்கையாழ்வார்","TamComp":"திருக்குறுந்தாண்டகம்"},
  {"Id":12,"Alvar":"Thirumangai Alwar","Comp":"Nedum Thandagam","TamAlvar":"திருமங்கையாழ்வார்","TamComp":"திருநெடுந்தாண்டகம்"},
  {"Id":13,"Alvar":"Poigai Alwar","Comp":"Mudhal Thiruvandhadhi","TamAlvar":"பொய்கையாழ்வார்","TamComp":"முதல் திருவந்தாதி"},
  {"Id":14,"Alvar":"Bhoodath Alwar","Comp":"Irandam Thiruvandhadhi","TamAlvar":"பூதத்தாழ்வார்","TamComp":"இரண்டாம் திருவந்தாதி"},
  {"Id":15,"Alvar":"Pei Alwar","Comp":"Moonram Thiruvandhadhi","TamAlvar":"பேயாழ்வார்","TamComp":"மூன்றாந் திருவந்தாதி"},
  {"Id":16,"Alvar":"Thirumazhisai Alwar","Comp":"Naanmugan Thiruvandhadhi","TamAlvar":"திருமழிசை ஆழ்வார் ","TamComp":"நான்முகன் திருவந்தாதி"},
  {"Id":17,"Alvar":"Nammalwar","Comp":"Thiruviruththam","TamAlvar":"நம்மாழ்வார்","TamComp":"திருவிருத்தம்"},
  {"Id":18,"Alvar":"Nammalwar","Comp":"Thiruvasiriyam","TamAlvar":"நம்மாழ்வார்","TamComp":"திருவாசிரியம்"},
  {"Id":19,"Alvar":"Nammalwar","Comp":"Peria Thiruvandhadhi","TamAlvar":"நம்மாழ்வார்","TamComp":"பெரிய திருவந்தாதி"},
  {"Id":20,"Alvar":"Thirumangai Alwar","Comp":"Thiruvezhukkurrirukkai","TamAlvar":"திருமங்கையாழ்வார்","TamComp":"திருவெழு கூற்றிருக்கை"},
  {"Id":21,"Alvar":"Thirumangai Alwar","Comp":"Siriya Thirumadal","TamAlvar":"திருமங்கையாழ்வார்","TamComp":"சிறிய திருமடல்"},
  {"Id":22,"Alvar":"Thirumangai Alwar","Comp":"Peria Thirumadal","TamAlvar":"திருமங்கையாழ்வார்","TamComp":"பெரிய திருமடல்"},
  {"Id":23,"Alvar":"Thiruvarangathu Amudhanaar","Comp":"Ramanuja Nootrandhadi","TamAlvar":"திருவரங்கத்தமுதனார்","TamComp":"இராமாநுச நூற்றந்தாதி"},
  {"Id":24,"Alvar":"Nammalwar","Comp":"Thiruvay Mozhi","TamAlvar":"நம்மாழ்வார்","TamComp":"திருவாய்மொழி"},
];

export var msongsDetails = [
  {"Id":1,"Name":"Song1","TamSong": ["\u0bae\u0bc0\u0ba9\u0bcd\u0ba8\u0bcb\u0b95\u0bcd\u0b95\u0bc1\u0bae\u0bcd \u0ba8\u0bc0\u0bb3\u0bcd\u0bb5\u0baf\u0bb2\u0bcd\u0b9a\u0bc2\u0bb4\u0bcd \u0bb5\u0bbf\u0bb1\u0bcd\u0bb1\u0bc1\u0bb5\u0b95\u0bcd\u0b95\u0bcb\u0b9f\u0bcd \u0b9f\u0bae\u0bcd\u0bae\u0bbe\u0b8e\u0ba9\u0bcd",
   "line2 \u0bae\u0bc0\u0ba9\u0bcd\u0ba8\u0bcb\u0b95\u0bcd\u0b95\u0bc1\u0bae\u0bcd \u0ba8\u0bc0\u0bb3\u0bcd\u0bb5\u0baf\u0bb2\u0bcd\u0b9a\u0bc2\u0bb4\u0bcd \u0bb5\u0bbf\u0bb1\u0bcd\u0bb1\u0bc1\u0bb5\u0b95\u0bcd\u0b95\u0bcb\u0b9f\u0bcd \u0b9f\u0bae\u0bcd\u0bae\u0bbe\u0b8e\u0ba9\u0bcd" ],
   "TamExpln": ["TamExpln1.1","TamExpln1.2"], "EngExpln": ["EngExpln1.1","EngExpln1.2"],"TamTblWords":["TblWord1","TblWord2"],"TamTblMeanings":["TblMng1","TblMng2"] },
  {"Id":2,"Name":"Song2","TamSong": ["TamSong Scripts2a","TamSong Scripts2b"],"TamExpln": ["TamExpln2.1","TamExpln2.2"], "EngExpln": ["EngExpln2.1","EngExpln2.2"], "TamTblWords":["TblWord1","TblWord2"],"TamTblMeanings":["TblMng1","TblMng2"]},
  {"Id":3,"Name":"Song3","TamSong": ["TamSong Scripts3"],"TamExpln": ["TamExpln3.1","TamExpln3.2"], "EngExpln": ["EngExpln3.1","EngExpln3.2"] ,"TamTblWords":["TblWord1","TblWord2"],"TamTblMeanings":["TblMng1","TblMng2"]},
  {"Id":4,"Name":"Song4","TamSong": ["TamSong Scripts4"],"TamExpln": ["TamExpln4.1","TamExpln4.2"], "EngExpln": ["EngExpln4.1","EngExpln4.2"] ,"TamTblWords":["TblWord1","TblWord2"],"TamTblMeanings":["TblMng1","TblMng2"]},
  {"Id":5,"Name":"Song5","TamSong": ["TamSong Scripts5"],"TamExpln": ["TamExpln5.1","TamExpln5.2"], "EngExpln": ["EngExpln5.1","EngExpln5.2"] ,"TamTblWords":["TblWord1","TblWord2"],"TamTblMeanings":["TblMng1","TblMng2"]},
  {"Id":6,"Name":"Song6","TamSong": ["TamSong Scripts6"],"TamExpln": ["TamExpln6.1","TamExpln6.2"], "EngExpln": ["EngExpln6.1","EngExpln6.2"] ,"TamTblWords":["TblWord1","TblWord2"],"TamTblMeanings":["TblMng1","TblMng2"]},
  {"Id":11,"Name":"Song11","TamSong": ["TamSong Scripts11"],"TamExpln": ["TamExpln11.1","TamExpln11.2"], "EngExpln": ["EngExpln11.1","EngExpln11.2"] ,"TamTblWords":["TblWord1","TblWord2"],"TamTblMeanings":["TblMng1","TblMng2"]},
  {"Id":12,"Name":"Song12","TamSong": ["TamSong Scripts12"],"TamExpln": ["TamExpln12.1","TamExpln12.2"], "EngExpln": ["EngExpln12.1","EngExpln12.2"] ,"TamTblWords":["TblWord1","TblWord2"],"TamTblMeanings":["TblMng1","TblMng2"]},
  {"Id":13,"Name":"Song13","TamSong": ["TamSong Scripts13"],"TamExpln": ["TamExpln13.1","TamExpln13.2"], "EngExpln": ["EngExpln13.1","EngExpln13.2"] ,"TamTblWords":["TblWord1","TblWord2"],"TamTblMeanings":["TblMng1","TblMng2"]},
  {"Id":102,"Name":"Song102","TamSong": ["TamSong Scripts102"],"TamExpln": ["TamExpln102.1","TamExpln102.2"], "EngExpln": ["EngExpln102.1","EngExpln102.2"] ,"TamTblWords":["TblWord1","TblWord2"],"TamTblMeanings":["TblMng1","TblMng2"]},
  {"Id":1003,"Name":"Song1003","TamSong": ["TamSong Scripts1003"],"TamExpln": ["TamExpln1003.1","TamExpln1003.2"], "EngExpln": ["EngExpln1003.1","EngExpln1003.2"] ,"TamTblWords":["TblWord1","TblWord2"],"TamTblMeanings":["TblMng1","TblMng2"]}
];
